"""inital db setup

Revision ID: 67f0d384b8ea
Revises: 
Create Date: 2024-12-20 01:36:33.773376

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "67f0d384b8ea"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
