"""updated password field name in users table

Revision ID: ecfa0b2f9742
Revises: dec502250767
Create Date: 2024-12-20 17:34:17.015005

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecfa0b2f9742"
down_revision: Union[str, None] = "dec502250767"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password", sa.String(), nullable=False, server_default="default_password"
        ),
    )
    op.alter_column("users", "password", server_default=None)
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "password")
    # ### end Alembic commands ###
